"""Constants for Aquarea devices."""

AQUAREA_COORDINATORS = "aquarea_coordinators"

AQUAREA_SWITCH_DELAY = 10.0
AQUAREA_SELECT_DELAY = 10.0
AQUAREA_CLIMATE_DELAY_SHORT = 5.0
AQUAREA_CLIMATE_DELAY_LONG = 10.0
